### ISSUE TITLE
Loading the Tensorflow Backend only once

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/autonomio#20]
How can we best do it this? I guess ideally so that the backend is loaded only once per browser session just like it would be in jupyter kernel session.

**Comment by m-anish** [comment]
I have a question. 

When is the tensorflow backend actually loaded in your python scripts. 

Is it in the following code in result.py?

```
tr = train(x,y,data,flatten=flatten,epoch=epoch,dims=dims,
			batch_size=batch_size,layers=layers,neuron_first=neuron_first,
			neuron_last=neuron_last,loss=loss,optimizer=optimizer,
			activation=activation,activation_out=activation_out)
```

**Comment by mikkokotila** [comment]
It's loaded when you call train_new() which in our case takes place through train() from autonomio.commands. This is kind of a worst case scenario as it means that for every search the backend is loaded separately.

**Comment by m-anish** [comment]
Hmm. I guess I need to understand this better to really comment on how to do it. I will start by running a few commands that you do looking at your code. Will revert then :)

**Comment by mikkokotila** [comment]
I think now would be a good time to resolve this, as we don't want to have the current way in the package (which is ready to go minus the jypyter as a service part) ;) Happy to discuss this more if you prefer to do it together.
