### ISSUE TITLE
Systematic Testing 

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/autonomio#25]
The process I had in mind looks like this: 

NOTE: Let's focus first on testing train(). 

**Preparation**
- take election, random_tweets, and parties datasets
- create 3 test that test a range of features

**Record in a csv log:** 

1) command that was performed
2) possible instructions related to the command for the user
3) prediction result (3 per command) 
4) any possible issues 
5) in the end summarize the commands in to a python script. 

For the file let's use a format where each argument in the train is a column, and then for each performed test there is value present for each argument (or is default is setting was not used) 

This will yield (in addition to helping to reveal where we are) the very important information we need for automation proper automated testing, i.e. the various commands that user would use. 

Thanks a lot for offering to do this, very useful!

**Comment by mikkokotila** [comment]
It would be good to see some outputs from the test...or I might start doing it myself ;)

**Comment by amitphan** [comment]
Will send over some results by EOD today. Planning to spend this afternoon on testing the various datasets

**Comment by amitphan** [comment]
I've tested close to 50 different train commands. here are some issues to track.
[qc_train.xlsx](https://github.com/autonomio/core-module/files/978053/qc_train.xlsx)

**Comment by mikkokotila** [comment]
This is great, thanks. At some point once we complete the current open tickets, I'll open a new one which focus on making the instructions better.

Just to be clear, does this also mean that in those 50 experiments, you did not find a single "bug". Not to say that would be a bad thing or anything... ;)

**Comment by amitphan** [comment]
What is the best way to post error messages. I'm getting multiple errors when using multiple columns -

eg - train([1,5], 'neg', data('random_tweets')) produces 
ValueError: Error when checking model input: expected dense_9_input to have shape (None, 300) but got array with shape (21517, 4)

and train([1,2,4,6,18], 'neg', data('random_tweets')) produces -
ValueError: could not convert string to float: None
