### ISSUE TITLE
Data rate exceeded

### ISSUE THREAD

**Issue by konchokdolma** [autonomio/autonomio#80]
When we are trying to vectorize text we get the message:

`IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
--NotebookApp.iopub_data_rate_limit`.

**Comment by mikkokotila** [comment]
This is a Jupyter related issue. Will mark it as a bug still, and close for now. If you find it, please update here.
